version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: docker/images/app/Dockerfile
    ports:
      - '3150:3150'
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PGHOST=db
      - PGUSER=postgres
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: postgres:12.1
    volumes:
      - $PWD/bin/db-setup:/bin/db-setup
    ports:
      - '5400:5432'
